#!/bin/bash

LOG_FILE="${TRIM_PKGVAR}/info.log"
PID_FILE="${TRIM_PKGVAR}/app.pid"

# write the command to start your program here 
CMD="${TRIM_APPDEST}/bin/docker-updater --fnos"

log_msg() {
    echo "$(date '+%Y-%m-%d %H:%M:%S') [INFO] $1" >> ${LOG_FILE}
}

log_err() {
    echo "$(date '+%Y-%m-%d %H:%M:%S') [ERROR] $1" >> ${LOG_FILE}
}

start_process() {
    if status; then
        return 0
    fi

    log_msg "正在启动应用进程..."
    # 启动应用进程
    bash -c "${CMD}" >> ${LOG_FILE} 2>&1 &
    local pid=$!
    printf "%s" "${pid}" > ${PID_FILE}

    # 探活检测启动状态
    sleep 1
    if ! check_process "${pid}"; then
        log_err "应用进程启动失败 (进程 PID: ${pid} 意外退出)。"
        rm -f "${PID_FILE}"
        return 1
    fi

    return 0
}

stop_process() {
    log_msg "正在停止应用进程..."

    if [ -r "${PID_FILE}" ]; then
        pid=$(head -n 1 "${PID_FILE}" | tr -d '[:space:]')
        
        log_msg "检测到运行中的进程 PID: ${pid}"
        if ! check_process "${pid}"; then
            # 进程不存在，清理无效 PID 文件
            rm -f "${PID_FILE}"
            log_msg "进程不存在，已清理残留 PID 文件"
            return
        fi

        log_msg "正在向进程 PID: ${pid} 发送 SIGTERM 停止信号..."
        kill -TERM ${pid} >> ${LOG_FILE} 2>&1

        local count=0
        while check_process "${pid}" && [ $count -lt 10 ]; do
            sleep 1
            count=$((count + 1))
            log_msg "等待进程终止... (${count}秒/10秒)"
        done

        if check_process "${pid}"; then
            log_err "进程 PID: ${pid} 未在 10 秒超时内停止，已发送 SIGKILL 强制杀掉进程。"
            kill -KILL "${pid}"
            sleep 1
            rm -f "${PID_FILE}"
        else
            log_msg "应用进程已成功停止。"
        fi
    fi

    return 0
}

check_process() {
    local pid=$1
    if kill -0 "${pid}" 2>/dev/null; then
        return 0  # process exist
    else
        return 1  # process not exist
    fi
}

status() {
    if [ -f "${PID_FILE}" ]; then
        pid=$(head -n 1 "${PID_FILE}" | tr -d '[:space:]')
        if check_process "${pid}"; then
            return 0
        else
            # Process is not running but pidfile exists - clean it up
            rm -f "${PID_FILE}"
        fi    
    fi

    return 1
}

case $1 in
start)
    # run start command. exit 0 if success, exit 1 if failed
    start_process
    ;;
stop)
    # run stop command. exit 0 if success, exit 1 if failed
    stop_process
    ;;
status)
    # check application status command. exit 0 if running, exit 3 if not running
    if status; then 
        exit 0
    else 
        exit 3
    fi
    ;;
*)
    exit 1
    ;;
esac